services:
  db:
    container_name: db
    image: postgres:14.11-bookworm
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
        - type: bind
          source: /home/ubuntu/deploy/following-storage
          target: /var/lib/postgresql/data
          bind:
            create_host_path: true
    shm_size: 512mb
    env_file:
      - ./postgres.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  feedgen:
    container_name: feedgen
    image: ghcr.io/theripperoni/feedgen:main
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./feedgen.env

  janitor:
    container_name: janitor
    image: ghcr.io/theripperoni/janitor:main
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./janitor.env

  jetstream:
    container_name: jetstream
    image: ghcr.io/theripperoni/jetstream:main
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./jetstream.env

  stats-viz:
    container_name: stats-viz
    image: ghcr.io/theripperoni/stats-viz:main
    restart: unless-stopped
    depends_on:
      - feedgen
    environment:
      - API_KEY=${API_KEY:-test-key}