services:
  db:
    container_name: db
    image: postgres:14.11-bookworm
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - ./postgres.env

  feedgen:
    container_name: feedgen
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-theripperoni}/feedgen:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./feedgen.env

  janitor:
    container_name: janitor
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-theripperoni}/janitor:latest
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./janitor.env

  jetstream:
    container_name: jetstream
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-theripperoni}/jetstream:latest
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./jetstream.env

  stats-viz:
    container_name: stats-viz
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-theripperoni}/stats-viz:latest
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - feedgen
    environment:
      - RSKY_API_KEY=${RSKY_API_KEY:-test-key}