[package]
name = "janitor"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenvy = "0.15"
chrono = "0.4.45"
cron = "0.15.0"
postgres = "0.19.9"
tokio = { version = "1", features = ["full"] }
axum = "0.8.9"
serde_json = "1.0.96"
serde = { version = "1.0", features = ["derive"] }