[package]
name = "lexicon"
version = "0.2.0"
edition = "2021"
publish = true
description = "Bluesky API library"
license = "Apache-2.0"
keywords = ["bluesky", "atproto"]

[dependencies]
cid = { version = "0.11.1", features = ["serde"] }
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_cbor = "0.11.2"
serde_bytes = "0.11.9"