[package]
name = "jetstream"
version = "0.1.0"
authors = ["Ripperoni <email@ripperoni.com>"]
description = "A framework for subscribing to the AT Protocol Jetstream, in Rust."
license = "Apache-2.0"
edition = "2021"
publish = true

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
lexicon = { workspace = true }
futures = "0.3.28"
tokio = { workspace = true }
tokio-tungstenite = { version = "0.28.0", features = ["native-tls"] }
axum = { workspace = true, features = ["macros"] }
tower-http = { version = "0.6.1", features = ["cors", "trace"] }
url = "2.3.1"
chrono = { workspace = true, features = ["serde"] }
reqwest = { version = "0.12.7", features = ["json", "rustls-tls"] }
serde = { workspace = true }
serde_json = { workspace = true }
cid = { version = "0.11.1", features = ["serde"] }
dotenvy = { workspace = true }
anyhow = { workspace = true }
