[package]
name = "feedgen"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
lexicon = { workspace = true }
axum = { workspace = true, features = ["macros"] }
tower-http = { version = "0.6.8", features = ["cors", "trace"] }
serde = { workspace = true }
serde_json = { workspace = true }
diesel = { version = "=2.1.5", features = ["chrono", "postgres", "r2d2"] }
deadpool-diesel = { version = "0.6.1", features = ["postgres"] }
dotenvy = { workspace = true }
chrono = { workspace = true }
ipld-core = "0.4.3"
base64 = "0.22.1"
bsky-sdk = "0.1.24"
identity = { workspace = true }
crypto = { workspace = true }
db-schema = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
sha2 = "0.10"
hmac = "0.12"
prometheus = { version = "0.13", features = ["process"] }

[dev-dependencies]
secp256k1 = { version = "0.31.1", features = ["global-context", "serde", "rand", "hashes"] }

