[package]
name = "feedgen"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
lexicon = { workspace = true }
axum = { version = "0.8.9", features = ["macros"] }
tower-http = { version = "0.6.8", features = ["cors", "trace"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "^1.0"
serde_json = "1.0.96"
diesel = { version = "=2.1.5", features = ["chrono", "postgres", "r2d2"] }
deadpool-diesel = { version = "0.6.1", features = ["postgres"] }
dotenvy = "0.15"
chrono = "0.4.45"
ipld-core = "0.4.3"
base64 = "0.22.1"
bsky-sdk = "0.1.24"
identity = { workspace = true }
crypto = { workspace = true }
db-schema = { workspace = true }
anyhow = "1.0.102"
tokio = { version = "1", features = ["full"] }
sha2 = "0.10"
hmac = "0.12"
prometheus = { version = "0.13", features = ["process"] }

[dev-dependencies]
secp256k1 = { version = "0.31.1", features = ["global-context", "serde", "rand", "hashes"] }

